server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core_farming?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3307/core_farming?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小连接数
      minimum-idle: 5
      #空闲连接的存活最大时间，默认60000（10分钟）
      idle-timeout: 180000
      #从连接池返回的连接的自动提交
      auto-commit: true
      #连接的最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间。默认30000（30秒）
      connection-timeout: 30000
      #超时连接是否可用的查询语句
      connection-test-query: SELECT 1

  # influxDB
  influx:
    url: http://127.0.0.1:8083
    user: root
    password: root
    database: test
    retention_policy: default
    retention_policy_time: 30d


  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost

  # Redis数据库索引（默认为0）
  redis:
    redisdatabase: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 12345
    #password: corewell
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

  jackson:
    time-zone: GMT+8

swagger:
  enabled: true
  title: swagger doc
  description: swagger doc
  base-package: com.corewell.study
  base-path: /**
  exclude-path: /error
  contract:
    name: aaa

mybatis:
  #配置mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  #配置mapper数据还回类型的别名（默认别名是类名）
  #mybatis.configuration.call-setters-on-nulls=true
  type-aliases-package: com.corewell.study.domain
  configuration-properties: classpath:mapper/mybatis-config.xml

  #mybatis sql 打印（方法接口所在的包，不是Mapper.xml 文件所在的包）
logging:
  level:
    com.corewell.study.dao: debug

jwt:
  #JWT 存储请求头
  tokenHeader: Authorization
  #JWT 加解密使用的秘钥
  secret: corewell
  # JWT的过期时间（60*60*24）
  expiration: 6864800
  #JWT 负载中拿到开头
  tokenHead: Bearer








#  ok:
#    http:
#      connect-timeout: 30
#      read-timeout: 30
#      write-timeout: 30
#  # 连接池中整体的空闲连接的最大数量
#      max-idle-connections: 200
#  # 连接空闲时间最多为 300 秒
#      keep-alive-duration: 300

