server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core_farming?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Redis数据库索引（默认为0）
  redis:
    redisdatabase: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    #spring.redis.password=
    password: 12345
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
    # 连接池中的最大空闲连接 默认 8
        max-idle: 8
    # 连接池中的最小空闲连接 默认 0
        min-idle: 0
swagger:
  enabled: true
  title: swagger doc
  description: swagger doc
  base-package: com.corewell.study
  base-path: /**
  exclude-path: error
  contract.name: aaa

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #mybatis.configuration.call-setters-on-nulls=true
  type-aliases-package: com.corewell.study.domain
  configuration-properties: classpath:mapper/mybatis-config.xml


