server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core_farming?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
swagger:
  enabled: true
  title: swagger doc
  description: swagger doc
  base-package: com.corewell.study
  base-path: /**
  exclude-path: error
  contract.name: aaa

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #mybatis.configuration.call-setters-on-nulls=true
  type-aliases-package: com.corewell.study.domain
  configuration-properties: classpath:mapper/mybatis-config.xml